### PR TITLE
Feature weight scheme implementation

### PR DESCRIPTION
**Pull request by MrSunshineVS**
Implemented each class according to the CRC, with some slight changes.
The method APIs for each of these functions have preconditions, make sure to read them before using them.
Also changed the name of "computeWeight" to "computeWeighted", since the function is really just giving the weighted average of a group of marks.
Decided to remove the "edit" and "move" etc. functions for both SimpleWeight and OrderedWeight, since any interactor should reasonably just create a new weight scheme for an assessment if anything like that were to change.
Also added some simple tests, please run them after modifying any files to ensure functionality still works as intended.

### CODE REVIEW

**Review by AlanC12138 — DISMISSED** [review]
Looks good! Great work.

**Review by samielsabri — CHANGES_REQUESTED** [review]
Great work! Consider making the following change:
We want the grade calculator to be able to work at any time of the semester, even when the User has only completed 2 out of the 3 Assessment instances within the assessment. As of now this third unfinished assessment instance would need to get assigned a dummy mark, but a more elegant solution would be to allow to pass in a list of marks within the SimpleWeight and OrderedWeight classes that can be less than Weight.numberOfInstances

**Review by samielsabri — APPROVED** [review]
Great! I appreciate how the changes reflect the proposed functionality and work well with the CourseManager Package

**Review by samielsabri — CHANGES_REQUESTED** [review]
Upon closer look, I am wondering whether you could add a getWeightPossible method for SimpleWeight as well?
Let's say I have an Assessment called "Quizzes" with three instances worth 0.1 each. I have committed two of them such that we will get [0.9, 0.7]. The running grade based on everything committed so far would thus be 0.8, but in order for this calculation to work, there would need to be a getCommittedWeight() within the Weight class or a similar mechanism based on the number of marks (I think the former solution would work better and wouldn't require dependency inversion)

**Pull request merged**
