### PR TITLE
39 the great refactor

### PR DESCRIPTION
**Pull request by MrSunshineVS**
This turned out to be a much bigger task than I initially thought. Thank you guys for being patient with this I know y'all wanted to get to work asap. Hopefully my work here will make it easier for us to finish the project :)

Notable entity changes include:
* (Almost) all entities are now abstract. The implementation of their data management is left to higher layers (like the database)
* factory interfaces have been moved to inside their respective classes.
* The Archive class now stores metadata about the state of the course when it was archived (what semester it was in, when was it archived). Course's "isArchived" attribute is now removed.
* The Semester class now has a "title" attribute that replaces the "semester" attribute in course
* The InstanceList class has been removed. Functionality is moved to Assessment.
* instances now have a LocalDateTime rather than a LocalDate and a LocalTime as their deadlines.
* GPA trend functionality has been moved to the usecases package and is separate from other entities.

Notable additions include:
* ports package: Contains a database package (for handling database boundaries) and a usecase package (for handling input boundaries).
* usecases package: Contains implementations of input boundaries from the ports package.
* InMemoryDB package: includes a fully formed in-memory database that allows saving/loading/querying/factorying? to and from a database that is contained entirely in memory. This package also contains in-memory implementations for entities.
* swingGUI package: an empty package that will later store the Model / View / Controller layer using the Java Swing suite.
* New tests: there are a variety of new test files, each with a TODO list of methods that need to be tested (not comprehensive). 

Notable removals/deprecations  include:
* usecases/dataStorage. The new inMemoryDB package handles everything with abstractions now so no need for the DsModels. I have kept them because they may help in implementing response models for the new usecases.
* usecases/markOperations. Obsolete with the new packaging system. I have kept them to repurpose their code.
* test/gradeTrend. The grade trend use case is now separate from any entities so the tests don't apply. I have kept them to repurpose their code for new tests.

I have included a few simple usecases in order to demonstrate how the new packages interact. Feel free to text me on discord or leave a review comment if you have any questions about how the new packages work or if you have changes you'd like to be made (or unmade).

Many files now contain "//TODO" comments that identify a particular feature that remains to be implemented. If you'd like to help out, take a look at these comments and text me if you need further elaboration.

### CODE REVIEW

**Review by AlanC12138 — APPROVED** [review]
crazy! Checked over all the changes, and there are lots of quality improvements. So far did not see anything problematic.

**Review by berrythebear — APPROVED** [review]
This really improves on following clean architecture!

**Review by DeepSJain — APPROVED** [review]
Overall, looks great.

**Review by samielsabri — APPROVED** [review]
Wow super impressive refactor! This will definitely help us move towards completion and adhere to the SOLID design principles

**Review by vaishnav8791 — APPROVED** [review]
Looks great to me, I really like how you considered clean architecture in this refactor.

**Pull request merged**
