### PR TITLE
made a bunch of edits and improvements based on comments of teammates…

### PR DESCRIPTION
**Pull request by samielsabri**
… on github

### CODE REVIEW

**Review by AlanC12138 — APPROVED** [review]
Looks good, nice job

**Review by DeepSJain — APPROVED** [review]
Looks good

**Comment by DeepSJain** [comment]
Allow InstanceList.addInstance to also work with AssessmentInstance as a parameter.

**Review by DeepSJain — COMMENTED** [review]
-

**Review by YuweiCai2003 — APPROVED** [review]
Looks good!

**Pull request merged**
