### PR TITLE
4 feature account class creation

### PR DESCRIPTION
**Pull request by AlanC12138**
completed use case: RemoveCourseFromArchiveUseCase
added removeCourseInputBoundary

added new GetCourseByCode method in Archiveimpl

### CODE REVIEW

**Review by vaishnav8791 — APPROVED** [review]
looks great to me ! the usecase and removeCourseInputBoundary look fine to me and reading through it.

**Review by samielsabri — APPROVED** [review]
looks good to me! i was doing my usecases similarly. maybe consider fixing the typo of "CourseDoesnotExists" but that's just a minor thing

**Review by DeepSJain — APPROVED** [review]
Looks good

**Review by YuweiCai2003 — APPROVED** [review]
Great!

**Pull request closed without merging**
