### PR TITLE
90 tests

### PR DESCRIPTION
**Pull request by AlanC12138**
tests for usecases in account and semester

### CODE REVIEW

**Review by vaishnav8791 — APPROVED** [review]
Test cases look good to me! The only issue right now looks like there is a conflict with the files.

**Review by MrSunshineVS — APPROVED** [review]
Good stuff!

**Review by vaishnav8791 — APPROVED** [review]
Great work and now looks perfect with branch conflict being taken care of.

**Review by berrythebear — APPROVED** [review]
Looks good!

**Review by DeepSJain — APPROVED** [review]

**Pull request merged**
