### PR TITLE
Login/Registration, AddCourse GUI

### PR DESCRIPTION
**Pull request by DeepSJain**
Login and Registration GUI for the application
AddCourse GUI

### CODE REVIEW

**Review by AlanC12138 — DISMISSED** [review]
Very neat structure! No problems found.

**Review by berrythebear — DISMISSED** [review]

**Review by AlanC12138 — DISMISSED** [review]
No problem.

**Review by samielsabri — DISMISSED** [review]
bug fixed thank you!

**Review by berrythebear — APPROVED** [review]

**Review by vaishnav8791 — APPROVED** [review]
Looks great to me.  Good work !

**Pull request merged**
