### PR TITLE
4 feature account class creation

### PR DESCRIPTION
**Pull request by AlanC12138**
Completed factories and interfaces for all account and course entities

### CODE REVIEW

**Review by samielsabri — APPROVED** [review]
great work alan! thanks so much for refactoring and creating those neat packages

**Review by MrSunshineVS — APPROVED** [review]
perfect! The account code is great and this really cleans up the project structure

**Review by berrythebear — APPROVED** [review]
Adheres to clean architecture.

**Review by DeepSJain — APPROVED** [review]
Good work

**Pull request merged**
